#!/usr/bin/env bash

THIS_DIR="$(realpath "$(dirname "${BASH_SOURCE[0]}")")"
cd "${THIS_DIR}" || exit $?

(

	echo '<head><style>'
	cat ./dist/bundle.css
	echo '</style></head>'
	echo '<div id="root"></div>'
	echo '<script>'
	cat ./dist/bundle.js
	echo '</script>'
) >./dist/index.html
